config/routes.rb
Rails.application.routes.draw do
  # admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # user sign-up
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }

  # search
  get '/search', to: 'searchs#index',as: :search_index

  # shopping_cart/
  namespace :shopping_cart do
     # cart_orders
    get ':id/order', to: 'cart_orders#show'
    post ':id/order', to: 'cart_orders#order'
     # carts
    get ':id', to: 'carts#index', as: :shopping_cart
    delete ':id/:cart_work_id', to: 'carts#destroy', as: :shopping_work
    post ':id/:cart_work_id', to: 'carts#update', as: :update
    patch ':id/:cart_work_id', to: 'carts#pass', as: :pass
  end

  # user/
  namespace :user do
    # follows
    get ':id/followed/index', to: 'follows#fed_index', as: :followed
    get ':id/follower/index', to: 'follows#fer_index', as: :follower
  end

  # history/
  namespace :history do
    get 'order', to: 'orders#index_order'
    get ':order_id/:id', to: 'orders#show_order', as: :order_show
    get 'sale', to: 'orders#index_sale'
    get 'sale/:id', to: 'orders#show_sale', as: :sale_show
  end

  #  config/
  namespace :config do
    resources :credits, only: [:edit, :update]
      # credits
    get 'credit/new', to: 'credits#credit_new'
    post 'credit', to: 'credits#credit_create', as: :credit_create
    delete 'credit/:id', to: 'credits#credit_destroy'
      # banks
    get 'bank/new', to: 'banks#bank_new'
    post 'bank', to: 'banks#bank_create'
  end
  get 'config', to: 'configs#index', as: :config_index
  delete 'config', to: 'configs#bank_destroy', as: :config_bank_destroy

  # work/
  namespace :work do
    post ':id/favorite', to: 'favorites#create', as: :favorite_new
    delete ':id/favorite', to: 'favorites#destroy', as: :favorite_delete
  end


  #  works
  resources :works, only: [:show, :edit, :new, :create, :update, :destroy]
     # ユーザの作品表示
  get 'user/:id/work', to: 'works#index', as: :my_work
     # カートに追加する作品
  post 'work/:id', to: 'works#add', as: :in_cart_work
     # フォローした作品を表示
  get 'work', to: 'works#collect_index', as: :follower_work


  # users
  resources :users, only: [:show, :edit, :destroy, :update]
     # user/cancel
  get 'user/:id/cancel', to: 'users#show_cancel', as: :cancel_user
  post 'user/:id/cancel', to: 'users#update_cancel'
     # user/follow
  post 'user/:id/follow', to: 'users#add', as: :follow_user
  delete 'user/:id/follow', to: 'users#follow_destroy'

  # top
  root to: 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/config/banks_controller.rb
class Config::BanksController < ApplicationController
  before_action :authenticate_user!

  # 銀行登録ページ表示機能
  def bank_new
  	@bank = Bank.new
  end

  # 銀行登録機能
  def bank_create
    @bank =Bank.new(bank_params)
    @bank.user_id = current_user.id
    if @bank.save
       redirect_to config_index_path
    else
       render :bank_new
    end
  end

  private
  def bank_params
  	params.require(:bank).permit(:bank_name, :branch_number, :account_number, :surname, :name)
  end
end

app/controllers/config/credits_controller.rb
class Config::CreditsController < ApplicationController
  before_action :authenticate_user!

  # 新規クレジット投稿表示
  def credit_new
    @credit = CreditCard.new
  end

  # 新規クレジット作成機能
  def credit_create
    @credit = CreditCard.new(credit_params)
    @credit.user_id = current_user.id
    if @credit.save
       redirect_to config_index_path
    else
       render :credit_new
    end
  end

  # クレジット編集画面表示
  def edit
    @credit = CreditCard.find(params[:id])
    if @credit.user_id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  # クレジット編集機能
  def update
    @credit = CreditCard.find(params[:id])
    if @credit.update(credit_params)
       redirect_to config_index_path
    else
       render :edit
    end
  end

  # クレジット削除機能
  def credit_destroy
    @credit = CreditCard.find(params[:id])
    @credit.destroy
    redirect_to config_index_path
  end

  private
  def credit_params
    params.require(:credit_card).permit(:name, :card_number, :month, :year, :cvc, :user_id)
  end
end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  before_action :authenticate_user!

  # ユーザ設定画面表示
  def index
    @credit = CreditCard.where(user_id: current_user.id)
    if @banks =Bank.find_by(user_id: current_user.id).nil? == false
      @banks = Bank.find_by(user_id: current_user.id)
      if @banks.bank_name == 1
    	  @bank_name = "三菱UFJ"
      elsif @banks.bank_name == 2
    	  @bank_name = "みずほ銀行"
      elsif @banks.bank_name == 3
      	  @bank_name ="三井住友銀行"
      elsif @banks.bank_name == 4
    	  @bank_name ="りそな銀行"
      end
    else
       @banks =Bank.find_by(user_id: current_user.id)
    end
  end

  # 銀行振込先削除機能
  def bank_destroy
  	@bank = Bank.find_by(user_id: current_user.id)
  	@bank.destroy
  	redirect_to config_index_path
  end
end

app/helpers/config/banks_helper.rb
module Config::BanksHelper
end

app/helpers/config/credits_helper.rb
module Config::CreditsHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/views/config/credits/credit_new.html.erb
<br><br>
<div class="container main1 bg-light">




  <div class="creditcard-new-title row col-lg-6 offset-lg-2">
    <h1><strong>Credit Card</strong></h1>
  </div>

  <!-- エラーメッセージ -->
  <div class="error-text offset-lg-3">
    <% if @credit.errors.any? %>
      <h6 class="text-danger"><%= @credit.errors.count %>件のエラーが発生しました</h6>
      <% @credit.errors.full_messages.each do |message| %>
        <h6 class="text-danger"><%= message %></h6>
      <% end %>
    <% end %>
  </div>



  <!-- クレジットカード登録欄 -->
  <%= form_for @credit, url: config_credit_create_path do |c| %>

    <br>
    <!-- カード名義人記入欄 -->
    <div class="creditcard-name row">
      <div class="row col-lg-3 offset-lg-3">
        <h4>カード名義人</h4><p>(半角ローマ字)</p>
      </div>
      <%= c.text_field :name, class: "col-lg-3" %>
    </div>

    <br>
    <!-- カード番号記入欄 -->
    <div class="creditcard-number row">
      <div class="row col-lg-3 offset-lg-3">
        <h4>カード番号</h4>
      </div>
      <%= c.number_field :card_number, class: "col-lg-3" %>
    </div>

    <br>
    <!-- 有効期限選択欄 -->
    <div class="creditcard-month-year row">
      <div class="row col-lg-3 offset-lg-3">
        <h4>有効期限</h4>
      </div>

      <%= c.select :month, [["01", "01"], ["02", "02"], ["03", "03"], ["04", "04"], ["05", "05"], ["06", "06"],["07", "07"], ["08", "08"], ["09", "09"], ["10", "10"], ["11", "11"], ["12", "12"]],:prompt => "Slect" %><a>月</a>

      <a> / </a>

      <%= c.select :year, [["19", "19"], ["20", "20"], ["21", "21"], ["22", "22"], ["23", "23"], ["24", "24"],["25", "25"], ["26", "26"]],  :prompt => "Slect" %>

      <a>年</a>
    </div>

    <br>
    <!-- セキュリティーコード記入欄 -->
    <div class="creditcard-cvc row">
      <div class="row col-lg-4 offset-lg-3">
        <h4>セキュリティコード</h4><p>(３桁)</p>
      </div>
      <%= c.number_field :cvc %>
    </div>

    <br>
    <!-- 登録ボタン -->
    <div class="creditcard-pass-create row col-lg-2 offset-lg-8">
      <%= c.submit "登録", class: "btn btn-dark" %>
    </div>

  <% end %>




<br>
</div>

app/views/config/credits/edit.html.erb
<br><br>
<div class="container main1 bg-light">



  <div class="creditcaerd-edit-title row col-lg-6 offset-lg-2">
    <h1><strong>Credit Card edit</strong></h1>
  </div>

  <!-- エラーメッセージ -->
  <div class="error-text offset-lg-3">
    <% if @credit.errors.any? %>
      <h6 class="text-danger"><%= @credit.errors.count %>件のエラーが発生しました</h6>
      <% @credit.errors.full_messages.each do |message| %>
        <h6 class="text-danger"><%= message %></h6>
      <% end %>
    <% end %>
  </div>



  <%= form_for @credit, url: config_credit_path(params[:id]), method: :PATCH do |c| %>

    <br>
    <!-- カード名義人記入欄 -->
    <div class="creditcard-edit-name row">
      <div class="row col-lg-3 offset-lg-3">
        <h4>カード名義人</h4><p>(半角ローマ字)</p>
      </div>
      <%= c.text_field :name, class: "col-lg-3" %>
    </div>

    <br>
    <!-- カード番号記入欄 -->
    <div class="creditcard-edit-number row">
      <div class="row col-lg-3 offset-lg-3">
        <h4>カード番号</h4>
      </div>
      <%= c.number_field :card_number, class: "col-lg-3" %>
    </div>

    <br>
    <!-- 有効期限選択欄 -->
    <div class="creditcard-month-yser row">
      <div class="row col-lg-3 offset-lg-3">
      <h4>有効期限</h4>
      </div>

      <%= c.select :month, [["01", "01"], ["02", "02"], ["03", "03"], ["04", "04"], ["05", "05"], ["06", "06"],["07", "07"], ["08", "08"], ["09", "09"], ["10", "10"], ["11", "11"], ["12", "12"]],:prompt => "Slect" %><a>月</a>


      <a> / </a>

      <%= c.select :year, [["19", "19"], ["20", "20"], ["21", "21"], ["22", "22"], ["23", "23"], ["24", "24"],["25", "25"], ["26", "26"]],  :prompt => "Slect" %>

      <a>年</a>

    </div>

    <br>
    <!-- セキュリティーコード記入欄 -->
    <div class="creditcard-edit-cvc row">
      <div class="row col-lg-4 offset-lg-3">
      <h4>セキュリティコード</h4><p>(３桁)</p>
      </div>
      <%= c.number_field :cvc %>
    </div>

    <br>
    <!-- クレジット編集ボタン -->
    <div class="creditcard-pass-edit row col-lg-2 offset-lg-8">
      <%= c.submit "Update", class: "btn btn-dark" %>
    </div>

    <br>
    <!-- クレジット削除ボタン -->
    <!-- ログイン者のみ表示 -->
    <% if @credit.user_id == current_user.id %>
      <div class="creditcard-pass-delete row col-lg-2 offset-lg-8">
        <%= link_to 'Card削除', config_path(params[:id]), method: :delete, class: 'btn btn-danger', "data-confirm" => "Are you sure?" %>
      </div>
    <% end %>

  <% end %>



<br>
</div>