config/routes.rb
Rails.application.routes.draw do
  # admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # user sign-up
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }

  # search
  get '/search', to: 'searchs#index',as: :search_index

  # shopping_cart/
  namespace :shopping_cart do
     # cart_orders
    get ':id/order', to: 'cart_orders#show'
    post ':id/order', to: 'cart_orders#order'
     # carts
    get ':id', to: 'carts#index', as: :shopping_cart
    delete ':id/:cart_work_id', to: 'carts#destroy', as: :shopping_work
    post ':id/:cart_work_id', to: 'carts#update', as: :update
    patch ':id/:cart_work_id', to: 'carts#pass', as: :pass
  end

  # user/
  namespace :user do
    # follows
    get ':id/followed/index', to: 'follows#fed_index', as: :followed
    get ':id/follower/index', to: 'follows#fer_index', as: :follower
  end

  # history/
  namespace :history do
    get 'order', to: 'orders#index_order'
    get ':order_id/:id', to: 'orders#show_order', as: :order_show
    get 'sale', to: 'orders#index_sale'
    get 'sale/:id', to: 'orders#show_sale', as: :sale_show
  end

  #  config/
  namespace :config do
    resources :credits, only: [:edit, :update]
      # credits
    get 'credit/new', to: 'credits#credit_new'
    post 'credit', to: 'credits#credit_create', as: :credit_create
    delete 'credit/:id', to: 'credits#credit_destroy'
      # banks
    get 'bank/new', to: 'banks#bank_new'
    post 'bank', to: 'banks#bank_create'
  end
  get 'config', to: 'configs#index', as: :config_index
  delete 'config', to: 'configs#bank_destroy', as: :config_bank_destroy

  # work/
  namespace :work do
    post ':id/favorite', to: 'favorites#create', as: :favorite_new
    delete ':id/favorite', to: 'favorites#destroy', as: :favorite_delete
  end


  #  works
  resources :works, only: [:show, :edit, :new, :create, :update, :destroy]
     # ユーザの作品表示
  get 'user/:id/work', to: 'works#index', as: :my_work
     # カートに追加する作品
  post 'work/:id', to: 'works#add', as: :in_cart_work
     # フォローした作品を表示
  get 'work', to: 'works#collect_index', as: :follower_work


  # users
  resources :users, only: [:show, :edit, :destroy, :update]
     # user/cancel
  get 'user/:id/cancel', to: 'users#show_cancel', as: :cancel_user
  post 'user/:id/cancel', to: 'users#update_cancel'
     # user/follow
  post 'user/:id/follow', to: 'users#add', as: :follow_user
  delete 'user/:id/follow', to: 'users#follow_destroy'

  # top
  root to: 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/config/banks_controller.rb
class Config::BanksController < ApplicationController
  before_action :authenticate_user!

  # 銀行登録ページ表示機能
  def bank_new
  	@bank = Bank.new
  end

  # 銀行登録機能
  def bank_create
    @bank =Bank.new(bank_params)
    @bank.user_id = current_user.id
    if @bank.save
       redirect_to config_index_path
    else
       render :bank_new
    end
  end

  private
  def bank_params
  	params.require(:bank).permit(:bank_name, :branch_number, :account_number, :surname, :name)
  end
end

app/controllers/config/credits_controller.rb
class Config::CreditsController < ApplicationController
  before_action :authenticate_user!

  # 新規クレジット投稿表示
  def credit_new
    @credit = CreditCard.new
  end

  # 新規クレジット作成機能
  def credit_create
    @credit = CreditCard.new(credit_params)
    @credit.user_id = current_user.id
    if @credit.save
       redirect_to config_index_path
    else
       render :credit_new
    end
  end

  # クレジット編集画面表示
  def edit
    @credit = CreditCard.find(params[:id])
    if @credit.user_id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  # クレジット編集機能
  def update
    @credit = CreditCard.find(params[:id])
    if @credit.update(credit_params)
       redirect_to config_index_path
    else
       render :edit
    end
  end

  # クレジット削除機能
  def credit_destroy
    @credit = CreditCard.find(params[:id])
    @credit.destroy
    redirect_to config_index_path
  end

  private
  def credit_params
    params.require(:credit_card).permit(:name, :card_number, :month, :year, :cvc, :user_id)
  end
end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  before_action :authenticate_user!

  # ユーザ設定画面表示
  def index
    @credit = CreditCard.where(user_id: current_user.id)
    if @banks =Bank.find_by(user_id: current_user.id).nil? == false
      @banks = Bank.find_by(user_id: current_user.id)
      if @banks.bank_name == 1
    	  @bank_name = "三菱UFJ"
      elsif @banks.bank_name == 2
    	  @bank_name = "みずほ銀行"
      elsif @banks.bank_name == 3
      	  @bank_name ="三井住友銀行"
      elsif @banks.bank_name == 4
    	  @bank_name ="りそな銀行"
      end
    else
       @banks =Bank.find_by(user_id: current_user.id)
    end
  end

  # 銀行振込先削除機能
  def bank_destroy
  	@bank = Bank.find_by(user_id: current_user.id)
  	@bank.destroy
  	redirect_to config_index_path
  end
end

app/helpers/config/banks_helper.rb
module Config::BanksHelper
end

app/helpers/config/credits_helper.rb
module Config::CreditsHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/views/configs/index.html.erb
<br>
<div class="container main2 bg-light">



  <div class="creditcard-title row col-lg-4 offset-lg-4">
    <h1><strong>Credit Card</strong></h1>
  </div>

  <!-- クレジットカード登録一覧 -->
  <% @credit.each do |c| %>
    <div class="creditcard-index row offset-lg-4">
      <% if c.card_number.slice(0..1) == "35" %>
        <h4>JCB**********<%= c.card_number.slice(11..15) %>クレジット</h4>
      <% elsif c.card_number.slice(0..1).in?([ "45", "42", "47", "49"]) %>
        <h4>VISA**********<%= c.card_number.slice(11..15) %>クレジット</h4>
      <% elsif c.card_number.slice(0..1).in?([ "51", "52", "53", "54"]) %>
        <h4>Master**********<%= c.card_number.slice(11..15) %>クレジット</h4>
      <% else %>
        <h4>**************<%= c.card_number.slice(11..15) %>クレジット</h4>
      <% end %>
      <div class="creditcard-pass-edit row col-lg-2 offset-lg-3">
        <%= link_to 'Card編集', edit_config_credit_path(c.id), class: 'btn btn-outline-secondary' %>
      </div>
    </div>
  <% end %>

  <br>
  <!-- カード追加ボタン -->
  <div class="creditcard-pass-add row">
  <%= link_to 'Card追加', config_credit_new_path, class: 'btn btn-primary offset-lg-5' %>
  </div>




  <!-- 銀行振込先表示 -->
  <br><br><br>
  <div class="bank-title row col-lg-3 offset-lg-4">
    <h1><strong>銀行振込先</strong></h1>
  </div>

  <div class="bank-index row offset-lg-4">
    <h4><%= @bank_name %>
    <% if Bank.find_by(user_id: current_user.id).nil? == false %>
    <%= @banks.branch_number %>
    <%= @banks.account_number %>
    <% end %>
    </h4>

    <!-- 銀行振込先登録時のみ表示 -->
    <% if Bank.find_by(user_id: current_user.id).nil? == false %>
      <div class="bank-pass-delete row col-lg-2 offset-lg-5">
        <%= link_to 'Delete', config_bank_destroy_path, method: :delete, class: 'btn btn-outline-danger', "data-confirm" => "Are you sure?" %>
      </div>
    <% end %>
  </div>

  <!-- 振込先追加ボタン -->
  <% if Bank.find_by(user_id: current_user.id).nil? == true %>
    <div class="bank-pass-add row`">
    <%= link_to '振込先登録', config_bank_new_path, class: 'btn btn-primary offset-lg-5' %>
    </div>
  <% end %>




<br>
</div>