config/routes.rb
Rails.application.routes.draw do
  # admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # user sign-up
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }

  # search
  get '/search', to: 'searchs#index',as: :search_index

  # shopping_cart/
  namespace :shopping_cart do
     # cart_orders
    get ':id/order', to: 'cart_orders#show'
    post ':id/order', to: 'cart_orders#order'
     # carts
    get ':id', to: 'carts#index', as: :shopping_cart
    delete ':id/:cart_work_id', to: 'carts#destroy', as: :shopping_work
    post ':id/:cart_work_id', to: 'carts#update', as: :update
    patch ':id/:cart_work_id', to: 'carts#pass', as: :pass
  end

  # user/
  namespace :user do
    # follows
    get ':id/followed/index', to: 'follows#fed_index', as: :followed
    get ':id/follower/index', to: 'follows#fer_index', as: :follower
  end

  # history/
  namespace :history do
    get 'order', to: 'orders#index_order'
    get ':order_id/:id', to: 'orders#show_order', as: :order_show
    get 'sale', to: 'orders#index_sale'
    get 'sale/:id', to: 'orders#show_sale', as: :sale_show
  end

  #  config/
  namespace :config do
    resources :credits, only: [:edit, :update]
      # credits
    get 'credit/new', to: 'credits#credit_new'
    post 'credit', to: 'credits#credit_create', as: :credit_create
    delete 'credit/:id', to: 'credits#credit_destroy'
      # banks
    get 'bank/new', to: 'banks#bank_new'
    post 'bank', to: 'banks#bank_create'
  end
  get 'config', to: 'configs#index', as: :config_index
  delete 'config', to: 'configs#bank_destroy', as: :config_bank_destroy

  # work/
  namespace :work do
    post ':id/favorite', to: 'favorites#create', as: :favorite_new
    delete ':id/favorite', to: 'favorites#destroy', as: :favorite_delete
  end


  #  works
  resources :works, only: [:show, :edit, :new, :create, :update, :destroy]
     # ユーザの作品表示
  get 'user/:id/work', to: 'works#index', as: :my_work
     # カートに追加する作品
  post 'work/:id', to: 'works#add', as: :in_cart_work
     # フォローした作品を表示
  get 'work', to: 'works#collect_index', as: :follower_work


  # users
  resources :users, only: [:show, :edit, :destroy, :update]
     # user/cancel
  get 'user/:id/cancel', to: 'users#show_cancel', as: :cancel_user
  post 'user/:id/cancel', to: 'users#update_cancel'
     # user/follow
  post 'user/:id/follow', to: 'users#add', as: :follow_user
  delete 'user/:id/follow', to: 'users#follow_destroy'

  # top
  root to: 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attachment :image

  # 論理削除機能
  acts_as_paranoid

  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_follows, source: :followed
  has_many :followers, through: :passive_follows, source: :follower
  has_many :credit_cards, dependent: :destroy
  has_many :goods, dependent: :destroy
  has_many :shopping_cart, dependent: :destroy
  has_one :bank

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :postal_code, presence: true, length: { is: 7 }, numericality: true
  validates :address, presence: true
  validates :phone_number, presence: true, numericality: true
  validates :email, presence: true
  validates :introduction, length: { maximum: 500 }

  # ユーザをフォロー
  def follow!(other_user)
  	active_follows.create(followed_id: other_user.id)
  end

  # ユーザをアンフォロー
  def unfollow!(other_user)
  	active_follows.find_by(followed_id: other_user.id).destroy
  end

  # 今のユーザがフォローしていたらtrueを返す
  def following?(other_user)
  	following.include?(other_user)
  end

  # ユーザ検索
  def self.search(keyword)
    if keyword
      where(['name LIKE ?', "%#{keyword}%"])
    else
      User.all
    end
  end

end

app/controllers/user/follows_controller.rb
class User::FollowsController < ApplicationController
  before_action :authenticate_user!

  # フォロー一覧表示機能
  def fed_index
  	@users = Follow.where(follower_id: params[:id]).page(params[:page]).per(13).order(followed_id: "DESC")
  	@user = User.find(params[:id])
  end

  # フォロワー一覧表示機能
  def fer_index
  	@users = Follow.where(followed_id: params[:id]).page(params[:page]).per(13).order(follower_id: "DESC")
  	@user = User.find(params[:id])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
      if current_user.nil?
        new_user_registration_path and return
      else
        @cart = ShoppingCart.new
        @cart.user_id = current_user.id
        @cart.is_active = "true"
        @cart.save
      end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # ユーザMy page表示機能
  def show
    @user = User.find(params[:id])
    @work = Work.where(user_id: params[:id])
  end

  # ユーザ編集画面表示
  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  # ユーザ退会機能
  def destroy
    @user = User.find(current_user.id)
    @user.destroy
    redirect_to root_path
  end

  # ユーザ編集機能
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(params[:id])
    else
       render :edit
    end
  end

  # フォロー機能
  def add
    @user = User.find(params[:id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  # フォロー解除機能
  def follow_destroy
    @user = User.find(params[:id])
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  private
  def user_params
    params.require(:user).permit(:postal_code, :address, :phone_number, :email, :image, :introduction, :gender)
  end
end

app/helpers/user/follows_helper.rb
module User::FollowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for user, url:follow_user_path(user), method: :post, remote: true do |f| %>
  <%= f.submit "Follow ＋", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless user == current_user %>
    <% if current_user.following?(user) %>
      <%= render 'users/unfollow', user: user %>
    <% else %>
      <%= render 'users/follow', user: user %>
    <% end %>
<% end %>

app/views/users/_stats.html.erb
<!-- フォロワー・フォロー人数表示 -->
<% @user ||= current_user %>
<div class="stats">
  <div><a href="<%= user_followed_path(@user) %>">
    <h2 id="following" class="stat text-dark">
      Follow:<%= @user.following.count %>
    </h2>
  </a></div>
  <div><a href="<%= user_follower_path(@user) %>">
    <h2 id="followers" class="stat text-dark">
      Follower:<%= @user.followers.count %>
    </h2>
  </a></div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for user, url:follow_user_path(user), method: :delete, remote: true do |f| %>
  <%= f.submit "Follow −", class: "btn btn-primary" %>
<% end %>

app/views/users/add.js.erb
$("#user_<%= @user.id %>").html("<%= escape_javascript(render 'users/unfollow', :user => @user) %>");
$("#followers").html('Follower:<%= @user.followers.count %>');

app/views/users/edit.html.erb
<div class="container main1 bg-light">

  <div class="row col-lg-3 offset-lg-2">
  <h1><strong>User edit</strong></h1>
  </div>

  <!-- エラーメッセージ -->
  <div class="error-text offset-lg-3">
    <% if @user.errors.any? %>
      <h6 class="text-danger"><%= @user.errors.count %>件のエラーが発生しました</h6>
      <% @user.errors.full_messages.each do |message| %>
        <h6 class="text-danger"><%= message %></h6>
      <% end %>
    <% end %>
  </div>

  <%= form_for(@user) do |f| %>

<!-- ユーザ画像表示 -->
  <div class="row col-lg-3 offset-lg-4">
  <%= attachment_image_tag @user, :image, :fill, 250, 300, fortmat: "jpg", fallback: "no-user-image.jpg", size: "250x300", class: "user-image-work" %>
  </div>

 <br>
<!-- ユーザ画像編集 -->
  <div class="row">
  	<div class="col-lg-3 offset-lg-3">
    <h4>image</h4>
    </div>
    <%= f.attachment_field :image %>
  </div>

<br>
<!-- 郵便番号編集 -->
  <div class="row">
  	<div class="row col-lg-3 offset-lg-3">
    <h4>郵便番号</h4><p>(ハイフンなし)</p>
    </div>
    <%= f.text_field :postal_code, class: "col-lg-3" %>
  </div>

<br>
<!-- 住所編集 -->
  <div class="row">
  	<div class="row col-lg-3 offset-lg-3">
    <h4>Address</h4>
    </div>
    <%= f.text_area :address, class: "col-lg-3" %>
  </div>

<br>
<!-- 電話番号編集 -->
  <div class="row">
  	<div class="row col-lg-3 offset-lg-3">
    <h4>電話番号</h4>
    </div>
    <%= f.text_field :phone_number, class: "col-lg-3" %>
  </div>

<br>
<!-- email編集 -->
  <div class="row">
  	<div class="row col-lg-3 offset-lg-3">
    <h4>E-mail</h4>
    </div>
    <%= f.text_field :email, class: "col-lg-3" %>
  </div>

<br>
<!-- 紹介文編集 -->
  <div class="row">
  	<div class="row col-lg-3 offset-lg-3">
    <h4>introduction</h4>
    </div>
    <%= f.text_area :introduction, class: "col-lg-3" %>
  </div>

<br>
<!-- 性別編集 -->
  <div class="row">
  	<div class="col-lg-2 offset-lg-4">
    <h4><%= f.radio_button :gender, "1" %> Male</h4>
    </div>
    <h4><%= f.radio_button :gender, "2" %> Female</h4>
  </div>

<!-- 編集ボタン -->
  <div class="row col-lg-2 offset-lg-8">
    <h6><%= f.submit "Update", class: "btn btn-dark" %></h6>
  </div>

  <% end %>

<br>
</div>

app/views/users/follow_destroy.js.erb
  $("#user_<%= @user.id %>").html("<%= escape_javascript(render 'users/follow', :user => @user) %>");
  $("#followers").html('Follower:<%= @user.followers.count %>');

app/views/users/show.html.erb
<br>
<div class="container main1 bg-light">

  <div class="row">
    <!-- ユーザ画像表示 -->
    <div class="row col-lg-3 col-md-6 offset-lg-3">
    <%= attachment_image_tag @user, :image, :fill, 250, 300, fortmat: "jpg", fallback: "no-user-image.jpg", size: "250x300",  class: "user-image-work" %>
    </div>

    <!-- フォロー・フォロワー・作品数表示 -->
    <div class="offset-lg-1">
      <h1><strong><%= @user.name %></strong></h1>
      <br>
      <br>
      <!-- ユーザ作品数 -->
      <%= link_to my_work_path(@user.id) do %>
      <h2 class="text-dark">My Works:<%= @work.count%></h2>
      <% end %>
      <!-- フォロワー・フォロー人数 -->
      <section class="stats">
      <%= render 'stats' %>
      </section>
      <!-- ユーザ編集ボタン -->
      <!-- ログイン者のみ表示 -->
      <% if @user.id == current_user.id %>
      <%= link_to "Edit", edit_user_path(@user.id), class: "btn btn-outline-secondary btn-sm col-lg-9" %>
      <% end %>
      <!-- フォローボタン -->
      <section id="user_<%= @user.id %>">
      <%= render 'follow_form', user: @user if signed_in? %>
      </section>
    </div>
  </div>



  <br>
  <!-- ライン -->
  <div class="col-lg-12" style="border-bottom: solid 3px #C0C0C0;"></div>



  <!-- ユーザ紹介文 -->
  <div class="user-introduction">
    <h3><strong>Introduction</strong></h3>
    <h5><%= @user.introduction %></h5>
  </div>

  <br>
  <% if @user.id == current_user.id %>
  <!-- フォローしたユーザの作品ボタン -->
  <div class="row">
    <%= link_to "<< My Collections >>", follower_work_path, class: "btn btn-primary btn-block btn-lg col-lg-8 offset-lg-2" %>
  </div>
  <% else %>
  <!-- ユーザ作品ボタン -->
  <div class="row">
    <%= link_to "<< Gallery >>", my_work_path(@user.id), class: "btn btn-primary btn-block btn-lg col-lg-8 offset-lg-2" %>
  </div>
  <% end %>

  <br>
  <!-- 購入・販売履歴ボタン -->
  <% if @user.id == current_user.id %>
  <div class="row">
    <%= link_to "Get history", history_order_path, class: "btn btn-outline-success btn-sm col-lg-4 offset-lg-2" %>

    <%= link_to "Sale history", history_sale_path, class: "btn btn-outline-warning btn-sm col-lg-4" %>
  </div>
  <% end %>

<br>
</div>