config/routes.rb
Rails.application.routes.draw do
  # admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # user sign-up
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }

  # search
  get '/search', to: 'searchs#index',as: :search_index

  # shopping_cart/
  namespace :shopping_cart do
     # cart_orders
    get ':id/order', to: 'cart_orders#show'
    post ':id/order', to: 'cart_orders#order'
     # carts
    get ':id', to: 'carts#index', as: :shopping_cart
    delete ':id/:cart_work_id', to: 'carts#destroy', as: :shopping_work
    post ':id/:cart_work_id', to: 'carts#update', as: :update
    patch ':id/:cart_work_id', to: 'carts#pass', as: :pass
  end

  # user/
  namespace :user do
    # follows
    get ':id/followed/index', to: 'follows#fed_index', as: :followed
    get ':id/follower/index', to: 'follows#fer_index', as: :follower
  end

  # history/
  namespace :history do
    get 'order', to: 'orders#index_order'
    get ':order_id/:id', to: 'orders#show_order', as: :order_show
    get 'sale', to: 'orders#index_sale'
    get 'sale/:id', to: 'orders#show_sale', as: :sale_show
  end

  #  config/
  namespace :config do
    resources :credits, only: [:edit, :update]
      # credits
    get 'credit/new', to: 'credits#credit_new'
    post 'credit', to: 'credits#credit_create', as: :credit_create
    delete 'credit/:id', to: 'credits#credit_destroy'
      # banks
    get 'bank/new', to: 'banks#bank_new'
    post 'bank', to: 'banks#bank_create'
  end
  get 'config', to: 'configs#index', as: :config_index
  delete 'config', to: 'configs#bank_destroy', as: :config_bank_destroy

  # work/
  namespace :work do
    post ':id/favorite', to: 'favorites#create', as: :favorite_new
    delete ':id/favorite', to: 'favorites#destroy', as: :favorite_delete
  end


  #  works
  resources :works, only: [:show, :edit, :new, :create, :update, :destroy]
     # ユーザの作品表示
  get 'user/:id/work', to: 'works#index', as: :my_work
     # カートに追加する作品
  post 'work/:id', to: 'works#add', as: :in_cart_work
     # フォローした作品を表示
  get 'work', to: 'works#collect_index', as: :follower_work


  # users
  resources :users, only: [:show, :edit, :destroy, :update]
     # user/cancel
  get 'user/:id/cancel', to: 'users#show_cancel', as: :cancel_user
  post 'user/:id/cancel', to: 'users#update_cancel'
     # user/follow
  post 'user/:id/follow', to: 'users#add', as: :follow_user
  delete 'user/:id/follow', to: 'users#follow_destroy'

  # top
  root to: 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord

  belongs_to :user
  has_one :order
  has_many :cart_works
  has_many :works, through: :cart_works, dependent: :destroy
  
end

app/controllers/shopping_cart/cart_orders_controller.rb
class ShoppingCart::CartOrdersController < ApplicationController
  before_action :authenticate_user!

  # 注文確認画面表示
  def show
    @order = Order.new
    @shoppingcart = ShoppingCart.find(params[:id])
    @credit = CreditCard.where(user_id: current_user.id)
    @cartworks = CartWork.where(shopping_cart_id: @shoppingcart.id)
    # 合計金額
    @pricesums = 0
  	@cartworks.each do |cw|
  	  if cw.size_id == 9
	    price = ((cw.quantity - 1) * (cw.work.price / 10)) + ( 82 * (cw.quantity - 1)) + 820 + cw.work.price
	    else
	    price = (cw.quantity * cw.work.price) + (cw.size.price * cw.quantity)
      end
    @pricesums += price
    end
  end

  # 注文機能
  def order
  	@order = Order.new(order_params)

  	@cartworks = CartWork.where(shopping_cart_id: params[:id])
    # 各作品合計金額保存機能
  	@cartworks.each do |cw|
  	  if cw.size_id == 9
	    price = ((cw.quantity - 1) * (cw.work.price / 10)) + ( 82 * (cw.quantity - 1)) + 820 + cw.work.price
	  else
	    price = (cw.quantity * cw.work.price) + (cw.size.price * cw.quantity)
      end
    cw.price = price
    cw.sale_status = 1
    end
    # orderテーブル保存機能
    @order.postal_code = current_user.postal_code
    @order.address = current_user.address
    @order.shopping_cart_id = params[:id]
    @order.status = 1
    if @order.save
       # CartWorkテーブルの更新
       @cartworks.update(cartwork_params)
       # shoppingCartテーブル　true => false 更新機能
       shoppingcart = ShoppingCart.find(params[:id])
       shoppingcart.is_active = false
       shoppingcart.update(shoppingcart_params)
       # ショッピングカート新規作成
       @shoppingcart = ShoppingCart.new
       @shoppingcart.user_id = current_user.id
       @shoppingcart.save
    else
       @shoppingcart = ShoppingCart.find(params[:id])
       @credit = CreditCard.where(user_id: current_user.id)
       @cartworks = CartWork.where(shopping_cart_id: @shoppingcart.id)
       @pricesums = 0
       @cartworks.each do |cw|
         if cw.size_id == 9
           price = ((cw.quantity - 1) * (cw.work.price / 10)) + ( 82 * (cw.quantity - 1)) + 820 + cw.work.price
         else
           price = (cw.quantity * cw.work.price) + (cw.size.price * cw.quantity)
         end
       @pricesums += price
       end
       render :show
    end

  end

  private
  def order_params
  	params.require(:order).permit(:date, :time, :credit_card_id)
  end
  def cartwork_params
  	params.permit(:price)
  end
  def shoppingcart_params
  	params.permit(:is_active)
  end
end

app/controllers/shopping_cart/carts_controller.rb
class ShoppingCart::CartsController < ApplicationController
  before_action :authenticate_user!

  # カート表示機能
  def index
  	@cartworks = CartWork.where(shopping_cart_id: (params[:id])).order(id: "DESC")
    # 合計計算
  	@pricesums = 0
  	@cartworks.each do |cw|
  	  if cw.size_id == 9
	    price = ((cw.quantity - 1) * (cw.work.price / 10)) + ( 82 * (cw.quantity - 1)) + 820 + cw.work.price
	  else
	    price = (cw.quantity * cw.work.price) + (cw.size.price * cw.quantity)
      end
      @pricesums += price
    end
    if ShoppingCart.find(params[:id]).user_id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  # サイズ変更機能
  def update
    cw = CartWork.find(params[:cart_work_id])
    cw.update(size_params)
    redirect_to shopping_cart_shopping_cart_path(params[:id])
  end

  # 枚数変更機能
  def pass
    cw = CartWork.find(params[:cart_work_id])
    if params[:status] == "0"
       cw.quantity += 1
       cw.save
    else
       cw.quantity -= 1
       cw.save
    end
    redirect_to shopping_cart_shopping_cart_path(params[:id])
  end

  # 作品カート内削除
  def destroy
  	cw = CartWork.find(params[:cart_work_id])
  	cw.destroy
    redirect_to shopping_cart_shopping_cart_path(params[:id])
  end

  private
  def size_params
  	params.require(:cart_work).permit(:size_id)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/shopping_cart/cart_orders_helper.rb
module ShoppingCart::CartOrdersHelper
end

app/helpers/shopping_cart/carts_helper.rb
module ShoppingCart::CartsHelper
end

app/views/shopping_cart/carts/index.html.erb
<div class="container main1 bg-light">

  <div class="row offset-lg-5">
    <h1><strong>My Cart</strong></h1>
  </div>

  <!-- ライン -->
  <div class="col-lg-12" style="border-bottom: solid 4px #C0C0C0;"></div>

  <% if @cartworks.empty? %>
    <h4 class="offset-lg-4">カートに追加された商品はありません</h4>
  <% else %>

  <% @cartworks.each do |cw| %>

  <br>
  <!-- 作品画像表示 -->
  <div class="row">
    <div class="col-lg-3">
      <%= attachment_image_tag cw.work, :image, :fill, 200, 200, :size => "200x200", fallback: "no-item-image.jpg" %>
    </div>


    <div class="row">
      <!-- 作品枚数変更ボタン -->
      <div class="col-lg-3 text-lg-center">
	    <div class="form-group form-inline">
		  <%= link_to '+', shopping_cart_pass_path(params[:id], cart_work_id: cw.id, status: 0), class:"btn-sm btn-light ", method: :patch %>
		  <% if cw.quantity >= 2 %>
		  <%= link_to '-', shopping_cart_pass_path(params[:id], cart_work_id: cw.id, status: 1), class:"btn-sm btn-light ", method: :patch %>
		  <% else %>
		  <%= link_to '-', shopping_cart_shopping_work_path(params[:id], cart_work_id: cw.id), class:"btn-sm btn-light ", method: :delete, data: { confirm: 'カートから商品を削除しますか？' } %>
		  <% end %>
		   <h5>枚数：<%= cw.quantity + cw.size.quantity %></h5>
		</div>
	  </div>

	  <!-- 作品枚数変更後の金額表示 -->
	  <div class="col-lg-3">
	    <h5><strong>¥
	    <% if cw.size_id == 10 %>
	    <%= ((cw.quantity - 1) * (cw.work.price/10)) + ( 82 * (cw.quantity - 1)) + 820 + cw.work.price %>
	    <% else %>
		<%= (cw.quantity * cw.work.price) + (cw.size.price*cw.quantity) %>
		<% end %>
		</strong></h5>
	  </div>

      <!-- 作品サイズ変更ボタン -->
      <div class="col-lg-5">
	    <%= form_for cw, url: shopping_cart_update_path(params[:id], cart_work_id: cw.id), method: :POST do |cs| %>
	    <%= cs.collection_select :size_id, Size.all, :id, :size, :prompt => "Select", class: "col-lg-1" %>
	    <%= cs.submit "変更", class: "btn btn-dark " %>
	    <% end %>
      </div>

      <!-- カート内作品削除ボタン -->
      <div class="col-lg-1">
	    <%= link_to '削除', shopping_cart_shopping_work_path(params[:id], cart_work_id: cw.id), class: "btn btn-danger", method: :delete, data: { confirm: 'カートから商品を削除しますか？' } %>
      </div>
    </div>

  </div>

    <!-- 作品タイトル、ユーザ名表示 -->
    <div class="item_detail" >
	  <table class="table table-sm">
	    <tr>
		  <th>Title</th>
		  <th>User Name</th>
		</tr>
		<tr>
		  <td><%= cw.work.work_name %></td>
		  <td><%= cw.work.user.name %></td>
		</tr>
	  </table>
	</div>

  <% end %>

    <!-- 作品全合計金額表示 -->
    <div class="col-lg-3 offset-lg-9">
	  <h2><strong>合計 ¥
	  <%= @pricesums %>
	  </strong></h2>
	</div>

    <!-- 注文確認ボタン -->
    <div class="col-lg-2 offset-lg-10">
    <%= link_to '注文確認', shopping_cart_path(params[:id]), class:"btn btn-primary", method: :get %>
    </div>

  <% end %>

<br>
</div>